export const GET_CAROUSEL_BEGIN = "GET_CAROUSEL_BEGIN";
export const GET_CAROUSEL_SUCCESS = "GET_CAROUSEL_SUCCESS";
export const GET_CAROUSEL_FAIL = "GET_CAROUSEL_FAIL";

export const GET_CATEGORY_BEGIN = "GET_CATEGORY_BEGIN";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL";

export const GET_PRODUCT_BEGIN = "GET_PRODUCT_BEGIN";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";
